name: npm

on:
  push:
    branches:
      - main
      - ci

env:
  RUST_LOG: debug
  CARGO_INCREMENTAL: 0
  MACOSX_DEPLOYMENT_TARGET: "10.13"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - run: |
          corepack enable
          pnpm i

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Install wasm target
        shell: bash
        run: |
          rustup target add wasm32-wasi

      - name:  Publish to npm
        uses: pnpm/action-publish@v1
        run: pnpm publish --access public --no-git-checks
        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
