name: npm

on:
  push:
    branches:
      - main
      - ci

env:
  RUST_LOG: debug
  CARGO_INCREMENTAL: 0
  MACOSX_DEPLOYMENT_TARGET: "10.13"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Install wasm target
        shell: bash
        run: |
          rustup target add wasm32-wasi

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - run: |
          corepack enable
          pnpm --filter=swc-plugin-canyon publish -f --no-git-checks --access=public --filter
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
